language: php

php:
  - 5.5
  - 7.0

env:
  - WP_VERSION=master
  - WP_VERSION=4.2

before_script:
  - composer install

script: ./vendor/bin/phpunit

cache:
  directories:
    - vendor/

notifications:
  email: false